### ISSUE TITLE
Can't install with Ubuntu - NameError: name 'sys_platform' is not defined

### ISSUE THREAD

**Issue by chevi** [robotframework/statuschecker#3]
OS Ubuntu 14.04 x32

`python setup.py install
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    install_requires = ['robotframework']
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2099, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2309, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2538, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2571, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2568, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
`

**Comment by pekkaklarck** [comment]
Which version?

**Comment by chevi** [comment]
robotstatuschecker-1.3

`sudo pip install robotstatuschecker
`
`
Downloading robotstatuschecker-1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PyabBc/robotstatuschecker/setup.py", line 42, in <module>
        install_requires = ['robotframework']
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2099, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2309, in requires
        dm = self._dep_map
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2538, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2571, in _compute_dependencies
        common = frozenset(reqs_for_extra(None))
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2568, in reqs_for_extra
        if req.marker_fn(override={'extra':extra}):
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.49-py2.7.egg/_markerlib/markers.py", line 109, in marker_fn
        return eval(compiled_marker, environment)
      File "<environment marker>", line 1, in <module>
    NameError: name 'sys_platform' is not defined
    `
    ----------------------------------------
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PyabBc/robotstatuschecker/`

**Comment by pekkaklarck** [comment]
That works for me without errors on Mint.

It seems you have `distribute` module installed which, as far as I know, is deprecated and merged back to `setuptools`. Could you try upgrading `pip` with `pip install --upgrade pip` and see does that fix the problem?

**Comment by chevi** [comment]
Thanks! I installed after:
> sudo  pip uninstall distribute
> sudo pip install --upgrade setuptools

**Comment by pekkaklarck** [comment]
Great!
