### ISSUE TITLE
"FAIL GLOB" fails if patternt contains "-"

### ISSUE THREAD

**Issue by mint-user** [robotframework/statuschecker#31]
**Pattern:**

FAIL GLOB:
Several failures occurred:

1) Page should have contained element '//span[contains(text(),'test\\-part\\-unit (EDB)')]' but did not.

2) Page should have contained element '//span[contains(text(),'PNC1-0000015')]' but did not.
---

**Run:**
$ python3 -m robotstatuschecker ~/nasc/exec_logs/main.xml
---

**Result:**
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xander/.local/lib/python3.8/site-packages/robotstatuschecker.py", line 324, in <module>
    rc = process_output(*sys.argv[1:])
  File "/home/xander/.local/lib/python3.8/site-packages/robotstatuschecker.py", line 68, in process_output
    result = StatusChecker().process_output(inpath, outpath)
  File "/home/xander/.local/lib/python3.8/site-packages/robotstatuschecker.py", line 77, in process_output
    result.suite.visit(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/visitor.py", line 87, in visit_suite
    suite.suites.visit(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/visitor.py", line 88, in visit_suite
    suite.tests.visit(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/itemlist.py", line 77, in visit
    item.visit(visitor)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/model/testcase.py", line 130, in visit
    visitor.visit_test(self)
  File "/home/xander/.local/lib/python3.8/site-packages/robotstatuschecker.py", line 83, in visit_test
    if TestStatusChecker(expected).check(test):
  File "/home/xander/.local/lib/python3.8/site-packages/robotstatuschecker.py", line 206, in check
    return self._check_message(test)
  File "/home/xander/.local/lib/python3.8/site-packages/robotstatuschecker.py", line 214, in _check_message
    if not self._message_matches(test.message, self.message):
  File "/home/xander/.local/lib/python3.8/site-packages/robotstatuschecker.py", line 167, in _message_matches
    matcher = Matcher(pattern, caseless=False, spaceless=False)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/utils/match.py", line 42, in __init__
    self._regexp = self._compile(self._normalize(pattern), regexp=regexp)
  File "/home/xander/.local/lib/python3.8/site-packages/robot/utils/match.py", line 50, in _compile
    return re.compile(pattern, re.DOTALL)
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range _1-0_ at position 232 (line 5, column 74)

---
Escaping with "\\" helps only if no digits near "-"

**Comment by aaltat** [comment]
Could you share also how you did use the status checker?

**Comment by mint-user** [comment]
```
$ tree
.
├── log
│   ├── log.html
│   ├── main.xml
│   └── report.html
└── rf_report.robot
```
Repeats with this script (rf_report.robot):
```
*** Settings ***
Library           SeleniumLibrary

*** Test Cases ***
Test FAIL GLOB with "-"
    [Documentation]    ---
    ...    FAIL GLOB:
    ...
    ...    2) Page should have contained element '//span[contains(text(),'PNC1-0000015')]' but did not.
    Fail    PNC1-0000015
```
Run test:
```
$ robot --outputdir ~/rf/log --output main.xml --report report.html --log log.html ~/rf
```
Run statuschecker:
```
$ python3 -m robotstatuschecker ~/rf/log/main.xml
```
Result:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)

...

  File "/usr/lib/python3.8/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range 1-0 at position 77
```



Environment:

```
$ pip3 list
Package                        Version             
------------------------------ --------------------
...
robotframework                 4.0.3               
...  
robotstatuschecker             2.0.3               
...
```

**Comment by pekkaklarck** [comment]
It's not about `-` but `[chars]` which is wildcard with glob patterns. If you have `[lot of different chars]` its possible it matches accidentally. The reason `-` affects this is that it can be used for specifying ranges like `[a-f]`.

You ought to be able to replace `[` with `?` (matches any single char, including `[`) or escape it like `[[]` (matches whatever is in side `[` and `]` which is just `[`. Replacing/escaping `]` shouldn't be needed but might be a good idea for consistency.

**Comment by mint-user** [comment]
> escape it like `[[]`

Thank you, it works:
```
FAIL GLOB:

2) Page should have contained element '//span[[]contains(text(),'PNC1-0000015')[]]' but did not.
```

```
Test failed as expected.

Original message:
2) Page should have contained element '//span[contains(text(),'PNC1-0000015')]' but did not.
```
